### ISSUE TITLE
Mapping error when EmployeeVM is mapped to Identity user (solved in an alternative way)

### ISSUE THREAD

**Issue by AhmedSuror** [trevoirwilliams/leave-management#1]
First of all, it is not an issue literally meaning, because you have changed the IdentityUser to Employee, but I've noticed that:
I didn't have to change IdentityUser to Employee, I've just changed the Id property type to string instead of int in EmployeeVM and 
all worked fine.
So, if you please tell me is that fine?

**Comment by trevoirwilliams** [comment]
Hello Ahmed,
This should be fine, but the bigger issue will be later when trying to access the Employee specific fields, you will need to make the change.
